defaults:
  - dataset: cifar10
  - override hydra/sweeper: orion

hydra:
  # makes sure each multirun ends up in a unique folder
  # the defaults can make overlapping folders
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.sweeper.experiment.name}/${hydra.sweeper.experiment.uuid}/${hydra.job.id}

  sweeper:
    # default parametrization of the search space
    params:
      optimizer:
        name: "choices(['Adam', 'SGD'])"
        lr: "uniform(0, 1)"
      dropout: "uniform(0, 1)"
      batch_size: "uniform(4, 16, discrete=True)"
      epoch: "fidelity(10, 100)"

    experiment:
      name: 'experiment'
      version: '1'

    algorithm:
      type: random
      config:
        seed: 1

    worker:
      n_workers: -1
      max_broken: 3
      max_trials: 100

    storage:
      type: legacy

      database:
        type: pickleddb
        host: 'database.pkl'

optimizer:
  name: 'Adam'
  lr: 0.01

epoch: 100
dropout: 0.6
batch_size: 8

# if true, simulate a failure by raising an exception
error: false
return_type: float

