"""Plugin metadata"""
__version__ = "1.0.0"
__descr__ = "Hydra Sweeper Plugin for Orion"
__license__ = "BSD-3-Clause"
__author__ = "Epistímio"
__author_short__ = "Epistímio"
__author_email__ = "pierre.delaunay@mila.quebec"
__copyright__ = "2017-2022, Epistímio"
__url__ = "https://github.com/Epistimio/hydra_orion_sweeper"
