name: style

on: [pull_request]

jobs:
  style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: [black, isort, pylint]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

    - name: Test with tox
      run: tox -e ${{ matrix.toxenv }}
